# Generated by Django 2.2 on 2022-06-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accnumber',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
