# Generated by Django 2.2 on 2022-06-07 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_accnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw',
            old_name='routingnumber',
            new_name='banknmae',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='pin',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(default='0', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
