# Generated by Django 2.2 on 2022-06-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220607_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
