# Generated by Django 2.2 on 2022-06-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220607_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='acctype',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
