# Generated by Django 2.2 on 2022-02-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211207_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountname', models.CharField(default='0', max_length=50)),
                ('accountnumber', models.CharField(default='0', max_length=50)),
                ('routingnumber', models.CharField(default='0', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='totalbonus',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='totalrefbonus',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='totalwithdrawals',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address2',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cardnumber',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cvc',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='exp',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='pro.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name_oncard',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zipcode',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='accountbalance',
            field=models.CharField(default='10', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='0', max_length=400),
        ),
    ]
