# Generated by Django 2.2 on 2022-02-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220214_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address2',
            new_name='address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='ssn',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
