# Generated by Django 2.2 on 2022-06-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_customuser_acctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tran',
            name='dis',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
