# Generated by Django 2.2 on 2022-02-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220214_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='id2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
